do update

diff --git a/ISGIT b/ISGIT
--- a/ISGIT
+++ b/ISGIT
@@ -1,2 +1,10 @@
 #!/bin/bash
-git rev-parse 2> /dev/null; [ $? == 0 ] && echo 1
+
+#check if current directory is svn repository
+
+git rev-parse 2> /dev/null
+if [ $? == 0 ]; then #check last command exit code
+	echo 1
+else
+	echo 0
+fi
diff --git a/ISSVN b/ISSVN
--- a/ISSVN
+++ b/ISSVN
@@ -1,2 +1,10 @@
 #!/bin/bash
-svn info > /dev/null 2>&1; [ $? == 0 ] && echo 1
+
+#check if current directory is svn repository
+
+svn info > /dev/null 2>&1
+if [ $? == 0 ]; then #check last command exit code
+	echo 1
+else
+	echo 0
+fi
